title: TeCSAR Lab
description: TeCSAR-UNCC â€” Datasets & projects in video understanding, smart retail, and anomaly detection
url: "https://tecsar-uncc.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

minimal_mistakes_skin: "mint"   # try: "default", "air", "mint", "dark", "sunrise"

defaults:
  - scope:
      path: ""
    values:
      layout: single
