title: TeCSAR Lab
description: TeCSAR-UNCC â€” Research in smart city
url: "https://tecsar-uncc.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

minimal_mistakes_skin: "mint"  # try "air", "mint", "sunrise", "dark"

defaults:
  - scope:
      path: ""
    values:
      layout: single
